### ISSUE TITLE
CSS is not generated when switching to a FSE theme

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#1673] opened 2023-05-24 09:28 UTC
### Description

When transferring to an FSE theme, the custom CSS for the Home page (in Pages) is not generated. 

### Step-by-step reproduction instructions

If you import some content via Template Cloud, you will have content on the Home page then, if you switch to the FSE theme (e.g.: Raft), the editor will put the original content in a Post Content block.

![image](https://github.com/Codeinwp/otter-blocks/assets/17597852/df0b459c-2210-447b-b3ca-31b601dab1cf)

If you go to FSE Editor and select the Front Page then view it, you will notice that the custom styling for the original content is missing.

To fix this, go to Pages > Home, where the original content is, and press Update. This will trigger the CSS generation for the page.

### Environment info

https://pastebin.com/i0f7Scax

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment] 2023-08-23 13:44
@HardeepAsrani, I can no longer reproduce this issue.

Do you think that this change https://github.com/Codeinwp/otter-blocks/pull/1827 can help with other themes?

**Comment by HardeepAsrani** [comment] 2023-08-24 06:50
@Soare-Robert-Daniel You can't reproduce it anymore with any themes at all?

**Comment by Soare-Robert-Daniel** [comment] 2023-08-24 12:52
Everything seems to work fine. I was also tested with Neve FSE.

ℹ️ A problem when testing this behavior is that Starter Sites use neve var CSS, which becomes invalid when you change the theme.

**Comment by HardeepAsrani** [comment] 2023-08-25 04:25
If that's the case then we can close the PR and issue as issue with CSS variables won't be solved anyway. Perhaps maybe @Codeinwp/qa-team can take a look with the current version of WordPress.org to confirm they also aren't able to reproduce the issue?

**Comment by irinelenache** [comment] 2023-08-28 07:13
@Soare-Robert-Daniel @HardeepAsrani Tested and i also wasn't able to reproduce it. Feel free to close this ✔️

**Closed** 2023-09-22 02:20 UTC
Labels: bug, released, medium
