### ISSUE TITLE
Upgrade Dependancies related to development 

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/otter-blocks#1605] opened 2023-04-10 10:37 UTC
### What problem does this address?

The WP development tools got some major changes:
- Upgrading to Node 14
- Using jest v29
- Fixing performance tests like https://github.com/WordPress/gutenberg/pull/48240
- Playwright migration
- Fixing flaky test 
- Also E2E for blocks like in https://github.com/WordPress/gutenberg/commit/0b12f97a2d685cd3c2f76358e8b9c31e9d5db3a1, following the example we can start introducing e2e for our blocks 

### What is your proposed solution?

Updating the dependency to be as much as possible similar to the Core

**Comment by HardeepAsrani** [comment] 2023-05-26 17:05
@Soare-Robert-Daniel This is duplicate of https://github.com/Codeinwp/otter-blocks/issues/1667 so we can close this or this is for something else?

**Comment by Soare-Robert-Daniel** [comment] 2023-05-29 07:15
We can close this

**Closed** 2023-05-30 00:12 UTC
Labels: new feature
