### ISSUE TITLE
Animation module breaks other plugin when is installed

### ISSUE THREAD

**Issue by MartinVoplakal** [Codeinwp/otter-blocks#670] opened 2022-01-02 10:06 UTC
When ale these plugins activated ([Perfecty Push Notifications](https://wordpress.org/plugins/perfecty-push-notifications/) and this plugin with enabled Blocks Animation Module), the functions of Push Notif. plugin ale broken. Exactly The orange bell on left bottom corner is sometimes visible sometimes not. If I turn the Animation Module off it is ok.

**Comment by HardeepAsrani** [comment] 2022-01-03 02:20
Hey @MartinVoplakal,

I tried to reproduce it but it kept on working for me all the times. Can you @irinelenache help us in reproducing this issue? Thank you!

**Comment by HardeepAsrani** [comment] 2022-01-03 02:27
@MartinVoplakal Just an update: we figured out what might be causing it with the help of Perfectly team. They've posted the details here: https://wordpress.org/support/topic/use-addeventlistener-in-animation-frontend-js/

**Comment by HardeepAsrani** [comment] 2022-01-03 02:57
Another issue related to animations is when the animating object is in the very bottom of the screen, the animation doesn't happen because of our scrolling logic.

Can you take over this @Soare-Robert-Daniel?

**Comment by Soare-Robert-Daniel** [comment] 2022-01-03 06:40
@HardeepAsrani, I think we can make the detection using the same technic as Progress Bar with [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by HardeepAsrani** [comment] 2022-01-03 16:10
@MartinVoplakal We've fixed it and it will be released in the next update which will come alongside WordPress 5.9. Thank you for reporting it to us!

**Closed by HardeepAsrani** 2022-01-03 16:10 UTC
Labels: bug, extension:animations
