### ISSUE TITLE
Stripe Integration in Otter

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/otter-blocks#679] opened 2022-01-10 16:23 UTC
@HardeepAsrani I have an interesting use-case. Display x block if a stripe subscription is active.

How do you think this can best work? integrated within the plugin? Is it a generic enough use-case?

I need it for a piece of text but can work also for selling banner spaces for e.g. 

My use-case in detail is that I wanna list 10 premium products once they pay a subscription, once they stop paying, they would be hidden automatically.

**Comment by HardeepAsrani** [comment] 2022-01-10 20:42
@Soare-Robert-Daniel Can you experiment a bit with it if possible? Stripe is not available here in India so harder for me to test.

**Comment by Soare-Robert-Daniel** [comment] 2022-01-11 08:38
@HardeepAsrani, @ineagu Checking if the subscription is active is not a big deal; we only need to make an API request at https://stripe.com/docs/api/subscriptions/list. Form 3-party integration has the same logic.

The problem is, how do we know what to check? We need the `customer` id.

Getting that customer ID can be tricky because this must be tied to the account. Looking at Stripe for WP, most of it is WooCommerce. At first glance, we do not need Stripe because we can check the subscription from WooCommerce. https://www.webtoffee.com/woocommerce-subscription-stripe-payment-gateway/

**Comment by Soare-Robert-Daniel** [comment] 2022-01-11 08:44
@ineagu, this extension is not too generic because we are limited by getting the `customer` ID. It is more like integrating with other plugins (WooCommerce) than Stripe.

**Comment by ineagu** [comment] 2022-01-11 11:44
@HardeepAsrani it's a bit of what I am wondering:

Does it make sense to try a direct stripe integration( they add more and more features), integration that we can use for multiple blocks ( buy button etc)

or

Just integrate with Woo for e.g

**Comment by HardeepAsrani** [comment] 2022-01-13 20:48
@ineagu @Soare-Robert-Daniel Is there a way to check via email ID?

Else if we also give a buy using Stripe thingy, we can save the stripes ID to user's WordPress account and use that to make the request.

We already have the extension for Woo, so user can just see if the current user has bought XYZ instead of checking via the Stripe API.

**Comment by ineagu** [comment] 2022-01-13 21:12
sure we would need to build some auth for stripe first and I guess it doesn't worth just for this unless we wanna build something like wp simple pay.

Integrating with woo should be easy I guess, not sure if there is a need

**Comment by Soare-Robert-Daniel** [comment] 2022-01-14 08:56
One thing we can do is to check the user email with the stripe customer email. The workflow looks like this:

1. Get all the customers ([API](https://stripe.com/docs/api/customers/list)) and check if the user's email is in this list. If it exits, get the ID.
2. Get the subscriptions for the customer ID - [API](https://stripe.com/docs/api/subscriptions/list)
3. Check if the subscription id provided in the Block exists in the retrieved list. We can have a subscription selector for the Block Inspector (we do something similar in Form integration when you need to choose a category).
4. Comparare the status:  `paid, pending, in_transit, canceled or failed`. We can show different blocks based on the status.

For single products, we can use this API: https://stripe.com/docs/api/orders_legacy/list  
But is marked as a legacy; this needs more investigation.

⚠️ We need to think of a method to secure the private key. This should be secured and only available to `admin`. It can only be changed, and in the interface, we show only the last characters (or a similar method).

**We can not have methods that leak the private key. Someone can steal customer data or money via transfer: https://stripe.com/docs/api/transfers**

**Comment by ineagu** [comment] 2022-01-14 09:00
oki, I guess we can have this on hold until we get better ideas for stripe.

**Closed** 2023-01-10 14:22 UTC
