### ISSUE TITLE
Critical issues collection

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#975] opened 2022-06-15 10:07 UTC
Creating this in order to have a bird's eye view / summary of the issues that need to be addressed. These issues mentioned below contain **fixes for some high-priority bugs** on important blocks.

Please keep in mind that this list is still in progress, we will let you guys know when things are ready, as I still need to catch up with Mihai about a couple of things and agree on the selection.

### Issues List
For now let's focus on fixing the bugs and push collectively in an upcoming release. No need to think about making any changes to the UI (unless critically needed). The list of issues below might be updated, and is open to suggestions.

- [x] #797  
- [x] #820 <- some UI tweaks for the refactored form
- [x] #980 
- [x] #799 
- [x] #883 
- [x] #976 
- [x] #991 

Will ping you on Slack to discuss further.

cc @Codeinwp/otter-team

**Comment by mghenciu** [comment] 2022-06-27 12:13
@HardeepAsrani for this release, please also make sure that the issue we discussed [on Slack](https://vertistudio.slack.com/archives/C02JC68P404/p1655734555109209) is fixed.
The one with having Pro Blocks visible/usable, just by using the ZIP, even if **I already reached the site limit**:
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/52494172/175938424-fac5cee3-f62c-4a73-aef4-972ec3fb94c2.png">

**Comment by HardeepAsrani** [comment] 2022-07-08 12:58
@mghenciu This should be fixed here: https://github.com/Codeinwp/otter-blocks/pull/1026#issuecomment-1178957706

**Comment by mghenciu** [comment] 2022-07-11 10:44
> @mghenciu This should be fixed here: [#1026 (comment)](https://github.com/Codeinwp/otter-blocks/pull/1026#issuecomment-1178957706) - the activation limit issue.

Using the Otter & Otter Pro dev builds, **YES** the Pro blocks are not available anymore, just by using the zip file.
___
I have 1 question only:

Do we need both instances for the Otter License field? I noticed we have one in the Otter Dashboard and one under Settings > General (if it's related to being compatible with older Otter versions, then it makes sense):

![image](https://user-images.githubusercontent.com/52494172/178247064-15ff9e38-9de8-4d0f-b26d-c1e2fe397eb9.png)

**Comment by selul** [comment] 2022-07-11 10:45
> (if it's related to being compatible with older Otter versions, then it makes sense):
Nope, it's a bug, it should be kept only in the dashboard.

**Comment by HardeepAsrani** [comment] 2022-07-11 13:06
@mghenciu @selul It shouldn't be happening in actual shipped files, probably you were using the development files? Let me know how you had things setup so I can reproduce but we hide the field from appearing. I can't reproduce it on my end so far. Also can't reproduce it on tastewp with Otter + Otter Pro from WPorg/TI Store.

**Comment by mghenciu** [comment] 2022-07-13 11:29
> @mghenciu @selul It shouldn't be happening in actual shipped files, probably you were using the development files? Let me know how you had things setup so I can reproduce but we hide the field from appearing. I can't reproduce it on my end so far. Also can't reproduce it on tastewp with Otter + Otter Pro from WPorg/TI Store.

It was the **Development build**, so I guess that's why is visible there. Didn't knew about this.
In Prod that panel is not present.

**Closed** 2022-07-14 13:55 UTC
Labels: Issue list
