### ISSUE TITLE
Review CSS

### ISSUE THREAD

**Issue by selul** [Codeinwp/otter-blocks#525] opened 2021-10-20 12:13 UTC
We need to review the CSS that we use in Otter to maximize the performance of the blocks that are used: 

A few challenges/feedback that I see right now: 

1. On a fresh install, without any block from otter we load automatically general style.css. We should load it iff we have Otter inside the current page. That file has around 70KB uncompressed 😟 
2.  Split CSS and load them only based on the blocks used, see https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/
2. Review CSS selectors, which are enormous, i.e `.wp-block-themeisle-blocks-about-author .wp-block-themeisle-author-image .author-image` could be turned into `.wp-block-themeisle-author-image .author-image` which does the same thing, we don't need the parent if the child has already the prefix inside it.
3. Review CSS prefix, only by changing the prefix from `wp-block-themeisle-blocks-about-author` to `wp-block-o-aa` I get at least 20% reduction in size. I understand the challenge of adding new selectors and keeping the old ones, but this is how  would I approach it: 
   - Control the prefix from a single place using a localized JS variable, i.e otter_namespace. The localized JS variable will use PHP to decide what prefix to use. If new install use `o` otherwise use legacy one. You can see if the site is a new install using `fresh_site` option added by core. We use that in Neve too. 
   - Each block-specific CSS class will use the same pattern. 
   - Provide a mechanism inside Otter pages for legacy sites, i.e non-fresh ones to convert their selectors to new ones.
4. Review CSS which can be loaded in Footer, let's say if we have blocks that have nonvisible elements or not visible in above the fold, it's better to load them in the footer. This will need to be tested on slow network connections to avoid CLS issues.

**Comment by HardeepAsrani** [comment] 2022-02-16 22:08
@selul 

> On a fresh install, without any block from otter we load automatically general style.css. We should load it iff we have Otter inside the current page. That file has around 70KB uncompressed 😟

That file is now less than 1kb so it should be fine.

> Split CSS and load them only based on the blocks used, see https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/

Already did that in the previous PR that was merged. Now we come across this issue where if 10 blocks from Otter are being used, we enqueue 10 different CSS files. Are you aware of anyway in WordPress to load it in one as some sort of CSS loader to avoid multiple requests?

> Review CSS selectors, which are enormous,

Mostly done. Left some as same files are being worked on other PRs.

> Review CSS prefix, only by changing the prefix from wp-block-themeisle-blocks-about-author to wp-block-o-aa I get at least 20% reduction in size. I understand the challenge of adding new selectors and keeping the old ones, but this is how would I approach it: 

This will only work for sub-classes as the main class such as `wp-block-themeisle-blocks-about-author` is auto-generated by the block and can't be changed.

For the sub classes, I think the issue is mostly with few blocks only as most don't have many CSS. A better approach might be to check if the Otter is already installed and run search/replace on each post when it's loaded for the first time. It will be a heavy operation but will only be done once for each post.

Also, this one point should be done in a smaller release with less stuff. Already too many big changes, better to avoid another. 😆 What do you think?

**Comment by selul** [comment] 2022-02-17 07:32
> Also, this one point should be done in a smaller release with less stuff. Already too many big changes, better to avoid another. 😆 What do you think?

Agree, maybe we can do this around 2 weeks after the main one?

> Already did that in the previous PR that was merged. Now we come across this issue where if 10 blocks from Otter are being used, we enqueue 10 different CSS files. Are you aware of anyway in WordPress to load it in one as some sort of CSS loader to avoid multiple requests?

Can't we add them in the generated CSS file that we do for each post?

**Comment by HardeepAsrani** [comment] 2022-02-17 13:13
@selul We can but those CSS files can change with each version of the block, while the generated CSS stays saved unless the user updates the page.

**Comment by HardeepAsrani** [comment] 2022-02-17 13:18
It'll look like this in the front:

`<link rel='[stylesheet]()' href='[http://localhost:8888/wp-admin/load-styles.php?c=0&amp;dir=ltr&amp;load%5Bchunk_0%5D=dashicons,admin-bar,buttons,media-views,editor-buttons,wp-components,wp-block-editor,wp-nux,wp-reusable-blocks,wp-editor,common,&amp;load%5Bchunk_1%5D=forms,wp-reset-editor-styles,wp-block-library,wp-editor-classic-layout-styles,wp-block-library-theme,wp-edit-blocks,wp-edit-post&amp;load%5Bchunk_2%5D=,code-editor,wp-block-directory,wp-format-library,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,w&amp;load%5Bchunk_3%5D=p-pointer,widgets,site-icon,l10n,wp-auth-check&amp;ver=5.9](view-source:http://localhost:8888/wp-admin/load-styles.php?c=0&dir=ltr&load%5Bchunk_0%5D=dashicons,admin-bar,buttons,media-views,editor-buttons,wp-components,wp-block-editor,wp-nux,wp-reusable-blocks,wp-editor,common,&load%5Bchunk_1%5D=forms,wp-reset-editor-styles,wp-block-library,wp-editor-classic-layout-styles,wp-block-library-theme,wp-edit-blocks,wp-edit-post&load%5Bchunk_2%5D=,code-editor,wp-block-directory,wp-format-library,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,w&load%5Bchunk_3%5D=p-pointer,widgets,site-icon,l10n,wp-auth-check&ver=5.9)' type="[text/css]()" media='[all]()' />`

**Comment by selul** [comment] 2022-02-17 13:22
I won't go into this right now, it might have issues with different hosting scenarios and setup. 

We can either do inline or use the generated CSS.

**Closed as completed** 2022-02-18 19:52 UTC
