### ISSUE TITLE
Allow live search in the popup

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1700] opened 2023-06-06 22:11 UTC
### What problem does this address?

An Agency client wants to add the Live Search block inside of a Popup block, but currently, the live search feature doesn't work in a popup. No results appear while typing.

Reported [here](https://secure.helpscout.net/conversation/2254437848/370877?folderId=212385).

### What is your proposed solution?

Allow the Live Search feature to be used in a Popup block.

**Comment by HardeepAsrani** [comment] 2023-06-07 07:19
Duplicate of https://github.com/Codeinwp/otter-internals/issues/91

**Closed by HardeepAsrani** 2023-06-07 07:19 UTC
Labels: new feature, customer report
