### ISSUE TITLE
Button Group from Otter not collapsing anymore

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#742] opened 2022-02-22 13:17 UTC
When adding a Button Group from Otter, there is an option to collapse those button on a certain device.
So when Collapse is enabled on a Button Group, it should look something like this (each button is Inline-block):
![image (4)](https://user-images.githubusercontent.com/52494172/155139933-09c0b8b3-4653-4b8d-9dfe-fb3c5ab76d06.png)

But it looks like this:
![image (5)](https://user-images.githubusercontent.com/52494172/155139981-9ccdd838-06cf-4479-b3e3-c9e5380d0177.png)

Otter Version 1.7.5
Wordpress version: 5.8.3

**Comment by Soare-Robert-Daniel** [comment] 2022-02-28 11:14
Fixed in the new version.

Tested with `v2` branch on WP 5.8, 5.9.

Preview link: https://drumdowntown.tastewp.com/2022/02/28/buttons/

```
Site name: Drum Downtown
URL: https://drumdowntown.tastewp.com
Username: robertino
Password: UQUoB8S3DHA
```

**Comment by HardeepAsrani** [comment] 2022-03-01 06:20
@Soare-Robert-Daniel Did you fix it now or was it already fixed in v2?

**Comment by Soare-Robert-Daniel** [comment] 2022-03-01 07:42
You fixed the issue in this commit https://github.com/Codeinwp/otter-blocks/commit/3a50b29592bf162a163bde963b874d9e747d87e7 in the `style.css` file on the `collapse` classes

The problem was that it used `display: block` instead of using flex properties like `flex-direction`.

**Comment by HardeepAsrani** [comment] 2022-03-01 07:46
@Soare-Robert-Daniel Yea, now I remember that I faced the issue while testing. I thought maybe it was brought up then when I tried to convert it to v2. Thanks! We can close if @irinelenache is satisfied with the it.

**Comment by irinelenache** [comment] 2022-03-01 09:47
@HardeepAsrani Checked with the v2 branch and the issue is fixed 👍

**Comment by HardeepAsrani** [comment] 2022-03-01 09:48
I'll close it then, thanks!

**Closed by HardeepAsrani** 2022-03-01 09:48 UTC
Labels: bug
