### ISSUE TITLE
While adding an image with Otter, the image's height and width change.

### ISSUE THREAD

**Issue by Atharvabillore01** [Codeinwp/otter-blocks#1145] opened 2022-08-29 10:49 UTC
**Description:**

With Otter installed & activated, if, if I’m adding an image in a post, in the frontend the image height and width will change immediately after loading.

**How to reproduce:**
1.Add new post.
2.Insert image with Otter installed & activated.
(for reference try uploading https://pbs.twimg.com/profile_images/1128920402128977920/5Fpfewf7_400x400.png image )
3.Check how the image loads in frontend

** Expected behaviour:**

When reloading, the inserted image with Otter should not reload size. 

**Current behaviour:**

Image changes size.

**Reference:**

https://user-images.githubusercontent.com/91140562/187183282-2e1cdc38-7140-4f4d-b424-a831c9d2c611.mp4

**Comment by HardeepAsrani** [comment] 2022-08-29 11:09
@Atharvabillore01 If you disable Otter after having the image insert and then reload, does it stop happen?

**Comment by Atharvabillore01** [comment] 2022-08-30 10:58
@HardeepAsrani yes

**Comment by HardeepAsrani** [comment] 2022-09-26 03:25
@irinelenache Can you try to reproduce it? It works fine on my side.

**Comment by irinelenache** [comment] 2022-09-28 06:54
@HardeepAsrani Thanks for checking, I can't reproduce it either, maybe it was some cache related issue on Atharva's instance. We can close it and will reopen if it happens again 👍

**Closed** 2022-09-28 06:56 UTC
Labels: bug, help wanted
