### ISSUE TITLE
Webpack error in recent update?

### ISSUE THREAD

**Issue by markdav** [Codeinwp/otter-blocks#596] opened 2021-11-04 13:17 UTC
I am recently seeing an webpack error on the production site with update of my site.

Wordpress Version: 5.8.1
ThemeIsle Otter: Version 1.7.1

It works fine in the admin view but not on the site, doesn't seem to matter if I change template so not sure if it's my customized template.  I see it in developer console on pages with the countdown timer or embedded maps.

```
3605:6 Uncaught ReferenceError: __webpack_require__ is not defined
    at eval (3605:6)
    at Object.3605 (themeisle-gutenberg-leaflet-block.min.js?ver=74af107fa60ed4a4053c337e0752df22:1)
    at themeisle-gutenberg-leaflet-block.min.js?ver=74af107fa60ed4a4053c337e0752df22:1
    at themeisle-gutenberg-leaflet-block.min.js?ver=74af107fa60ed4a4053c337e0752df22:1
DevTools failed to load source map: Could not load content for https://craughwellac.com/site/wp-content/plugins/otter-blocks/assets/leaflet/leaflet-gesture-handling.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

See [sample page here](https://craughwellac.com/site/facilities/).

The blank spaces there are supposed to be maps.

**Comment by HardeepAsrani** [comment] 2021-11-05 19:21
Hey @markdav,

That's weird. We tried and weren't able to reproduce this on our end with a test website. Can you reinstall Otter from WordPress.org to make sure it still happens?

If it does then we can try to look at the issue on your site to see what could be causing it. Also, can you export that block, in particular, using this plugin so we get a better idea of what all settings are being used? https://wordpress.org/plugins/blocks-export-import/

Thank you!

**Comment by markdav** [comment] 2021-11-06 13:23
Thanks Hardeep - I did the "delete" and re-install and get the same errror - I installed that import/export plugin and get the following:

```
{
  "__file": "wp_export",
  "version": 2,
  "content": "<!-- wp:themeisle-blocks/leaflet-map {\"id\":\"wp-block-themeisle-blocks-map-b3f140d9\",\"location\":\"Craughwell, Co. Galway\",\"latitude\":\"53.23242724492917\",\"longitude\":\"-8.74671364144888\",\"bbox\":\"-8.764085769653322,53.222171426222246,-8.72941017150879,53.24272169747503\",\"zoom\":14,\"markers\":[{\"latitude\":53.236214750582036,\"longitude\":-8.748214206854511,\"id\":\"95525092-89ad-4698-9e98-2a2cdd223cd5\",\"title\":\"Craughwell AC Athletics Park\",\"description\":\"\\u003cp\\u003eThe home of Athletics in Craughwell!\\u003c/p\\u003e\"}]} /-->"
}
````

As I say, it works just fine on the dashboard/edit page view:

![image](https://user-images.githubusercontent.com/5741188/140611228-9b5cf0b6-a7b1-4fab-a289-ab0e94e2f2a7.png)

But not on the live site as you can see..

Thanks!

**Comment by HardeepAsrani** [comment] 2021-11-07 17:32
Hey @markdav,

It appears it's happening because you're using Siteground's Assets optimizer which is conflicting with the build files of Otter. You should exclude the otter scripts from it to make it work.

Let me know if that does it for you.

**Comment by markdav** [comment] 2021-11-09 19:14
Thanks @HardeepAsrani - very well spotted!  Excluding otter 

/plugins/otter-blocks//build/animation/frontend.js

didn't seem to work so I needed to disable the minification fill stop.

**Comment by HardeepAsrani** [comment] 2021-11-10 17:26
@markdav You should pretty much exclude all scripts in otter-blocks/build/blocks/ for frontend. The animation script isn't the one causing the error. You can still run the plugin with rest of the scripts.

**Comment by HardeepAsrani** [comment] 2021-11-13 02:05
I'm closing this for now. Let me know if that fixes it. Feel free to reopen the issue.

**Closed by HardeepAsrani** 2021-11-13 02:05 UTC
Labels: question
