### ISSUE TITLE
Section paddings overwrite themselves

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/otter-blocks#23] opened 2019-01-23 13:47 UTC
Section paddings get overwritten by themselves in some situations. 

![image](https://user-images.githubusercontent.com/15010186/51610747-2b77ca80-1f26-11e9-96ab-106346090338.png)

**Comment by abaicus** [comment] 2019-01-23 13:49
More precisely the linked paddings overwrite the unlinked paddings. cc @HardeepAsrani

**Comment by HardeepAsrani** [comment] 2019-01-24 09:09
@abaicus That happens because you've duplicated the section, so it has the same unique ID as the previous section.

So you will have to remove the ID attribute by default. It's an issue that I've fixed in development.

**Comment by HardeepAsrani** [comment] 2019-01-24 19:43
Closing as it's a duplicate of https://github.com/Codeinwp/otter-blocks/issues/25

**Closed by HardeepAsrani** 2019-01-24 19:43 UTC
