### ISSUE TITLE
Replace Image popup visible, on Feedback exit

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/otter-blocks#1265] opened 2022-10-17 12:48 UTC
### Description:

As seen in the video below the Image Replacement modal is visible when an user exist the Dynamic Images Tab.

### How to reproduce:

1. Open a page made with Otter
2. Add an Image there
3. Try to replace using a Dynamic Image
4. From the Dynamic Image tab, open the Feedback form
5. Close the Feedback form

### Current behaviour:
Using Neve:

https://user-images.githubusercontent.com/52494172/196180568-7818ecb5-fd49-419e-81e3-ae076e781921.mov

Using Generate Press:

https://user-images.githubusercontent.com/52494172/196180588-0b3efa6f-7722-447d-a040-e9debca737bd.mov

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.0.16

**Comment by mghenciu** [comment] 2022-10-18 09:49
> @mghenciu I tried with Neve and seems to work fine for me everytime.

By following this Repro Steps (video attached)?

This is a fresh instance with Neve. I am on latest Chrome & latest macOS.

https://user-images.githubusercontent.com/52494172/196397468-ade880a4-f04f-4340-b847-cf25197e4d7c.mov

**Comment by HardeepAsrani** [comment] 2022-11-09 20:38
I tried once again with Development branch on both Chrome/Firefox and it doesn't seem to be an issue: https://www.loom.com/share/51476945c64b4c4d9fc0aa00da627b48

Can you help us @irinelenache to confirm if it's not happening only on Mihai's side, or not happening only on my side?

**Comment by irinelenache** [comment] 2022-11-10 10:34
@HardeepAsrani The issue is happening as Mihai said, using **Otter version 2.0.16**. It is not happening with the latest version, tried to check on browserstack also, so the issue might be fixed now 👍

**Comment by HardeepAsrani** [comment] 2022-11-14 09:25
I'll close it then. Thank you!

**Closed by HardeepAsrani** 2022-11-14 09:25 UTC
Labels: bug
