### ISSUE TITLE
Otter section: Inherit content width from theme

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/otter-blocks#1388] opened 2022-12-12 14:49 UTC
This idea is about automatically inheriting the website’s content width as the Otter Section width.
[Inspired from Kadence 3](https://www.kadencewp.com/blog/what-to-expect-with-kadence-blocks-3-0)

Currently, the only way to have a specific content width is by manually adding the width value.

![Screenshot 2022-12-12 at 4 43 49 PM](https://user-images.githubusercontent.com/4193672/207074874-59f7ce6b-49fa-4d97-b3c7-9dbf5471e6ec.png)

It might be worth noting that all FSE themes include specifications for normal and wide withs. Maybe we can take advantage of these as well.

![Screenshot 2022-12-12 at 4 47 42 PM](https://user-images.githubusercontent.com/4193672/207075404-8a9eb295-f8b7-4f85-9f3c-1300e2bbeb7c.png)

Will elaborate in the meeting!
cc @HardeepAsrani @mghenciu

**Comment by HardeepAsrani** [comment] 2023-01-04 09:01
@JohnPixle I tried it and it's pretty tricky to do this well:

- First the issue is with how FSE themes define content width, we can get these working well with classic themes but not with FSE themes.
- It's hard to get the width inside the editor as themes can have different custom width based on different post types, page templates and even allowing you to define it while editing the post as Neve has, so we don't know what will be value of content width and it can change, so it's not possible for us to save it in the CSS.


It might actually be easier to make it work with specific themes, like Neve, but an overall solution looks hard to do that works well with all the themes and in both sides of the website.

**Comment by HardeepAsrani** [comment] 2023-01-11 17:31
@JohnPixle Yea, that's the issue that I had too, it's even hard to mentally workout what is it that we want to achieve here as by default the Section will be the width of the area. I'll close it for now, thanks for checking out the behavior with Kadence.

**Closed by HardeepAsrani** 2023-01-11 17:31 UTC
