### ISSUE TITLE
Flip cards styling disappears from the first flip card in the row

### ISSUE THREAD

**Issue by ghel1** [Codeinwp/otter-blocks#1821] opened 2023-08-21 20:37 UTC
### Description

I have 3 flip cards that appear in a row.  I have applied background colors and font colors to all cards and they look good in preview.   When I save the page the styling for the first card is lost.  The styling in the other two cards is fine.  I have switch to another theme with the same result.  I've deactivated all other plugins except for Guttenberg and Otter blocks.  Since this is a WP Engine site I can't disable their Must Use plugins.
I've also tried regenerating Otter blocks CSS files, but no difference.
I am using the latest version of Otterblocks Version 2.3.3.  The issues was present in the previous version as well.

### Step-by-step reproduction instructions

1. create 3 flip cards in a row
2. add colors styles for each front and back
3. save page
4. view page first flip card is white with back text
5. other two cards are styled appropriately

### Screenshots, screen recording, code snippet or Help Scout ticket

![preview](https://github.com/Codeinwp/otter-blocks/assets/16121424/f93bc9a6-6bc7-4fe2-9fcf-81ecf3982ce6)
![saved-version](https://github.com/Codeinwp/otter-blocks/assets/16121424/38260fdb-458e-41bf-bd61-4204437a0ec5)

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment] 2023-08-24 07:31
I could not reproduce the bug.

https://github.com/Codeinwp/otter-blocks/assets/17597852/b88e137c-4541-4e9a-a021-8000a5a113a5

----

ℹ️  @ghel1, does the issue still happen if you recreate the first flip block? If it still happens, please copy the block that contains the flips and paste it here 🙏  (video below)

https://github.com/Codeinwp/otter-blocks/assets/17597852/46602bd6-a8c0-4a9f-8c06-886c24ca5912

**Comment by ghel1** [comment] 2023-08-24 14:55
Yes, the problem still persists.  While the styles are there in the preview they are not when I save and view the page.
Thanks for looking into this!

Here are the blocks:


<div id="wp-block-themeisle-blocks-advanced-columns-f628554a" class="wp-block-themeisle-blocks-advanced-columns has-3-columns has-desktop-equal-layout has-tablet-equal-layout has-mobile-collapsedRows-layout has-vertical-unset"><div class="wp-block-themeisle-blocks-advanced-columns-overlay"></div><div class="innerblocks-wrap">
<div id="wp-block-themeisle-blocks-advanced-column-fd4bd420" class="wp-block-themeisle-blocks-advanced-column">
<div id="wp-block-themeisle-blocks-flip-7e7becf5" class="wp-block-themeisle-blocks-flip anim flipY has-dark-back-bg"><div class="o-flip-inner"><div class="o-flip-front"><div class="o-flip-content"><h3>sjljfaljf</h3><p></p></div></div><div class="o-flip-back">
<h3 class="wp-block-heading has-maximum-yellow-red-color has-metallic-red-background-color has-text-color has-background">dsaljlsdjafkj</h3>



<p class="has-text-color" style="color:#ffdead">Text</p>



<div class="wp-block-buttons">
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-luminous-vivid-orange-background-color has-background wp-element-button">button</a></div>
</div>
</div></div></div>
</div>



<div id="wp-block-themeisle-blocks-advanced-column-f5340e2c" class="wp-block-themeisle-blocks-advanced-column">
<div id="wp-block-themeisle-blocks-flip-a66f7090" class="wp-block-themeisle-blocks-flip anim flipY has-light-front-bg has-light-back-bg"><div class="o-flip-inner"><div class="o-flip-front"><div class="o-flip-content"><h3></h3><p></p></div></div><div class="o-flip-back">
<h3 class="wp-block-heading has-yellow-sun-background-color has-background"></h3>



<p></p>



<div class="wp-block-buttons"></div>
</div></div></div>
</div>



<div id="wp-block-themeisle-blocks-advanced-column-fa7a0309" class="wp-block-themeisle-blocks-advanced-column">
<div id="wp-block-themeisle-blocks-flip-d96cc3ce" class="wp-block-themeisle-blocks-flip anim flipY has-light-front-bg has-light-back-bg"><div class="o-flip-inner"><div class="o-flip-front"><div class="o-flip-content"><h3></h3><p></p></div></div><div class="o-flip-back">
<h3 class="wp-block-heading"></h3>



<p></p>



<div class="wp-block-buttons"></div>
</div></div></div>
</div>
</div></div>


From: Soare Robert Daniel ***@***.***>
Date: Thursday, August 24, 2023 at 3:31 AM
To: Codeinwp/otter-blocks ***@***.***>
Cc: Guy Chalk ***@***.***>, Mention ***@***.***>
Subject: Re: [Codeinwp/otter-blocks] Flip cards styling disappears from the first flip card in the row (Issue #1821)

      External Email - Use Caution





I could not reproduce the bug.

https://github.com/Codeinwp/otter-blocks/assets/17597852/b88e137c-4541-4e9a-a021-8000a5a113a5

________________________________

ℹ️ @ghel1<https://github.com/ghel1>, does the issue still happen if you recreate the first flip block? If it still happens, please copy the block that contains the flips and paste it here 🙏 (video below)

https://github.com/Codeinwp/otter-blocks/assets/17597852/46602bd6-a8c0-4a9f-8c06-886c24ca5912

**Comment by Soare-Robert-Daniel** [comment] 2023-08-25 06:45
I checked out the provided sample, and the issue is simple: the first flip block has a Gradient as a type of color, but no gradient color has been chosen.

Here is a showcase of the behavior:

https://github.com/Codeinwp/otter-blocks/assets/17597852/e7af2cd2-0cc0-4c66-9319-fc5e8000b673

----
 
🔧  The solution is to press the Color tab so the block can use the color you see.

**Comment by Soare-Robert-Daniel** [comment] 2023-09-14 09:54
@HardeepAsrani, I tested a proxy view in the background controller to commit the type of background only on a change, but the experience is not too good.

https://github.com/Codeinwp/otter-blocks/assets/17597852/ab3368ef-b258-4582-b401-dfc5193840ce

I was checking Elementor to see their approach, and their approach is like ours.

https://github.com/Codeinwp/otter-blocks/assets/17597852/e53cc182-0fc4-4948-8cdf-d712163db180

----

I will close this, it is not an issue.

**Closed** 2023-09-18 13:43 UTC
Labels: bug, small, customer report
