### ISSUE TITLE
Slow Typing after adding multiple blocks (seems to need optimization)

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/otter-blocks#799] opened 2022-03-15 07:03 UTC
When using multiple blocks whilst being on the latest version, you will start encountering slow typing in the Edit mode. I tried narrowing it down to a number of blocks to be used until you encounter this issue and it got me to approximately 20 blocks (more or less) for a new page.

If I try the same method on an already existing page, then the number decreases to about 5.

This issue was reported by one of our users and we initially thought it was an edge case but I think it has something to do with some optimization issue as I could replicate it multiple times on multiple instances.

Steps to reproduce:

1) Install the latest version of Otter
2) Edit an existing page (or create a new one but you'll need to add more blocks)
3) Start adding Otter Blocks to the said page
4) At some point, you'll notice that if you try to write (name a button, paragraph, heading etc) there is a noticeable delay from the moment you type on the keyboard to when the letters actually appear in the block

Expected behavior:
No delay from the input

Current Behavior:
Noticeable delayed text input

Reference:
[User Reported Here](https://secure.helpscout.net/conversation/1813047537/313355?folderId=212390)
[Screencast showing the current behavior after adding 5 new Otter blocks to an existing page](https://vertis.d.pr/spZl3B)

Testing instance:
User: admin
Pass: r6y7olamFiSYQGAjVLy9St)F
Website: https://spottedsun.s2-tastewp.com/wp-admin

Environment:
WP Version:5.9.2
Otter Version: 2.0.1

**Comment by preda-bogdan** [comment] 2022-03-17 18:02
I've opened here a draft PR with some changes that I made that from my testing improve the performance here:
https://github.com/Codeinwp/otter-blocks/pull/813

The biggest gain however came from disabling:
```
//import './conditions/index.js';
//import './css-handler/index.js';
//import './data-logging/index.js';
//import './menu-icons/index.js';
```

I think this is due to the fact that if you write inside the editor it will trigger a render on the sidebar components. If those components do a lot of work and they are not memoized they will rerender for every keystroke.
I used React Devtools to check rerenders, it can be set to highlight rerenders, elements that don't change should not rerender when in view.

I added some guards for `useEffect()` when using setTimeout or setInterval, it always has to return a cleanup routine to avoid memory leaks. Also when working with async calls if we need to update State we need to provide some guards to make sure the component is still mounted.

I encountered a few errors that I will mention here:
```
Warning: React does not recognize the `keepPlaceholderOnFocus` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `keepplaceholderonfocus` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Cause icon-list/item/edit.js:168 The property I think does not exist on the component.


You can check my findings by using this branch: https://github.com/Codeinwp/otter-blocks/tree/test/otter_performance

How I tested:
1. Created a post that has 4-5 blocks it does not matter what blocks.
2. Publish the post, exit, and go back to edit it.
3. Add 2-3 Otter blocks then start spamming text

With the version from `master` it will increase memory consumption rapidly.
With the version from the PR it is more stable.

This is not a complete FIX, it's just a starting point and sharing of my findings.

**Comment by mghenciu** [comment] 2022-03-18 14:49
Apparently it's also happening when using the Custom CSS for blocks.
Basically when starting to type some Custom CSS for a block in the sidebar, the writing gets really slow, compared to the previous versions of Otter.

**Comment by HardeepAsrani** [comment] 2022-03-20 17:24
@mghenciu Thanks, I'll keep that in mind. I think we can improve that part.

**Comment by mghenciu** [comment] 2022-03-24 08:23
As discussed yesterday in the meeting, I tried using a different browser (non chromium based), and there I don't have any browser extensions. -> **But the issue happened there also**. So I don't think this is browser related, nor caused by an extension.

___
My repro steps:
1. Open an existing page made with Otter, or create one with Otter 2.0.1
2. Add a Advanced Heading block on the page
3. Starting typing relatively fast
4. Notice how chars don't appear, and there is a delay between keyboard input and what you see on the screen

**Comment by selul** [comment] 2022-03-24 08:32
@mghenciu just to confirm, the latest version with the fix from here https://github.com/Codeinwp/otter-blocks/pull/813#issuecomment-1074379155 does not cause any improvements?

**Comment by mghenciu** [comment] 2022-03-24 09:08
> @mghenciu just to confirm, the latest version with the fix from here [#813 (comment)](https://github.com/Codeinwp/otter-blocks/pull/813#issuecomment-1074379155) does not cause any improvements?

Tested now, and **Yes** - **there's definitely an improvement** with this build. So if you type with an 1-2 words/second speed, you won't notice it at all.
___
And as Matei mentioned, it get's noticeable only after adding more blocks. For example with 3 Core + 2 Otter blocks -> no noticeable issue. 
But after copying the content of an Otter page and adding it on the Testing instance (12+ Otter blocks and 30 at least overall) -> the delay starts to be noticeable.

**Comment by selul** [comment] 2022-03-24 09:09
@abaicus @preda-bogdan keeping you in the loop in case that you see any further improvements.

**Comment by HardeepAsrani** [comment] 2022-04-02 00:21
Any updates on this? Might be good if we can compare Otter to other Block plugins and see if it's something that we do causes the slowdown or just adding 20-25 blocks to Gutenberg does that? Can you help with that @Skystream96?

**Comment by Skystream96** [comment] 2022-04-08 08:02
Hello @HardeepAsrani ,

We have a new customer stating the same issue [here](https://secure.helpscout.net/conversation/1839454052/316767?folderId=212385).

As for testing, I couldn't see such behavior reproduced with only Gutenberg thus I'm not sure what else can influence this behavior as there is no apparent similarity between the instances. Maybe it's about server resources and CPU?

**Comment by abaicus** [comment] 2022-04-08 11:53
I took a deeper look here. What @preda-bogdan proposed in PR #813 are great improvements. It seems that there's a big difference in the performance of that branch.

- The exponential typing delay that happens over time is probably because of all the `useEffect` hooks that never get cleaned up; this was addressed by Bogdan in the PR.

- As Bogdan mentioned, there are still unkeyed maps (having `SCRIPTS_DEBUG` defined and using React Devtools would throw an error for each of those errors during development), for example [here](https://github.com/codeinwp/otter-blocks/blob/c2b66724587e6a133f70fc110b8156709cf41c75/src/animation/components/animation-popover.js#L100). We should make sure to check all the `Array.map` functions and see if the return elements are unkeyed.

- Do we have a reason for not having an entry file for the `blocks.js` script with imports? We are now bundling everything through WebPack. I feel it would be easier to debug if you could exclude each part individually. This also leads to the build process being unreliable some of the times, so you have to restart it: 
![image](https://user-images.githubusercontent.com/15010186/162428824-0d407c3d-0bc8-4a03-9dfe-b522c8273552.png)

- It seems that the masonry extension could benefit from an early return if the block is not of gallery type [here](https://github.com/codeinwp/otter-blocks/blob/08f5a1f342348f5bbee764531601a33a11bd8de8/src/blocks/plugins/masonry-extension/index.js#L39-L41) so we don't try executing the function. Let's check all `createHigherOrderComponent` to ensure they are executed only when the context is proper.


Some things that I think would help in the future:

- I've seen that static data is formatted according to how core controls use it instead of using a more efficient format that would ease interaction with it on our end, and we could remap and cache it for the controls (as it would rarely change in that instance). e.g., The data [here](https://github.com/codeinwp/otter-blocks/blob/de12cf074e42a6fe4e2d0ae90caec79fbf650d92/src/animation/data.js#L6-L395) could be formatted as an object.  This way, we'd avoid searches through the array [here](https://github.com/codeinwp/otter-blocks/blob/49ba67ecd8efae26725a868ab763a035ac1f6df7/src/animation/editor.js#L58-L84). This might not yield huge performance benefits for small lists, where it's fine to do that, but on big lists in multiple places, it might make a difference.

- We could consider refactoring the icon picker and building the icons dynamically, similar to how we do it in the Neve Pro mega menu module. I think that instead of importing the full SVG list in the icon picker, we could probably use `<i>` tags and leverage the icon sets CSS. Then we can import the SVG only inside the editor body if it is used. Their size in the end build is pretty large:
![127 0 0 1_8888_](https://user-images.githubusercontent.com/15010186/162196379-183fd6d8-391e-4241-8f83-5dfa926f7ba0.png)


As far as I could identify, these are the more obvious things.

**Comment by Skystream96** [comment] 2022-04-10 10:40
Hello @HardeepAsrani ,

I have created a new test instance where I tried your suggestion to use other Block Builders (Kadence and Stackable) and it seems like Kadence has the same issue whilst Stackable encountered no issues.

I created 3 different pages with the same "Feature" layout with all 3 builders and Stackable didn't show any signs of bad performance even when creating more blocks than the rest. I tried reading the performance recording when typing new text into the blocks for both Stackable and Otter but couldn't find an exact cause. 

Here is the performance recording between Stackable
![Screenshot 2022-04-10 at 13 25 33](https://user-images.githubusercontent.com/82535909/162613801-638eef47-5d1b-4624-a5d2-31c1ac1f9325.png)


and Otter

![Screenshot 2022-04-10 at 13 25 43](https://user-images.githubusercontent.com/82535909/162613814-82926c8b-e60d-469c-9aaf-1a7ce673ce39.png)

and Kadence:

![Screenshot 2022-04-10 at 13 29 19](https://user-images.githubusercontent.com/82535909/162613957-b36fe39d-b44e-432d-ba8d-ed2811fa99f2.png)

When it comes to direct user input, it seems like both Kadence and Otter start encountering issues after 15 blocks were added whilst Stackable had no issues.

You can access this instance and check further as I have created 3 different pages with a similar layout, thinking it might help in finding the discrepancies in the back end easier.

Website: https://newattack.s1-tastewp.com
User: newattack@tastewp.com
Password: Z*)(xspS48V5U#t!YI1f8b)e

Thank you and hopefully, this will help!

**Comment by Skystream96** [comment] 2022-04-13 07:40
+1 https://secure.helpscout.net/conversation/1844363106/317328/

**Comment by HardeepAsrani** [comment] 2022-04-22 03:13
@preda-bogdan @abaicus We had to remove most of the `memo` and `useCallback` wrappers from the code as they were causing the editor to break.

**Comment by stefan-cotitosu** [comment] 2022-04-22 07:58
+1 https://secure.helpscout.net/conversation/1856979287/318683/

**Comment by selul** [comment] 2022-06-22 09:41
@Soare-Robert-Daniel based on Matei's report other block plugins are pretty good on the same environment, see https://github.com/Codeinwp/otter-blocks/issues/799#issuecomment-1094241690

**Comment by Soare-Robert-Daniel** [comment] 2022-06-22 09:44
@selul I tested them and got the same behavior. Kadence was even worse because when I started the profiler it let me use the page after 25 seconds.

**Comment by selul** [comment] 2022-06-22 09:46
maybe @Skystream96 can share how he tested

**Comment by Soare-Robert-Daniel** [comment] 2022-06-22 09:52
This is a simple run on Stackable.

https://user-images.githubusercontent.com/17597852/174999954-16060bfc-1df0-4505-b6f6-411b224ec4de.mp4

A lot of lag even in block Duplication.

**Comment by Soare-Robert-Daniel** [comment] 2022-06-30 13:58
I discussed this with @Skystream96, and the problem is persisting even in Stackable.

The general slowness is similar to Otter.  The difference is more sizable on fast typing. On stackable, a very fast written sentence will appear in two half chunks, while in Otter it will appear all at once.

**Closed** 2022-07-14 13:55 UTC
Labels: bug, investigate, released, optimization, merged
