### ISSUE TITLE
PHP errors after 2.1.2 upgrade

### ISSUE THREAD

**Issue by dave-andersen** [Codeinwp/otter-blocks#1315] opened 2022-11-09 19:47 UTC
### Description:
PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /sites/enrichedag/wp-includes/blocks.php:20
Stack trace:
#0 /sites/enrichedag/wp-includes/blocks.php(20): strpos()
#1 /sites/enrichedag/wp-includes/blocks.php(84): remove_block_asset_path_prefix()
#2 /sites/enrichedag/wp-includes/blocks.php(316): register_block_script_handle()
#3 /sites/enrichedag/wp-content/plugins/otter-blocks/inc/class-registration.php(801): register_block_type_from_metadata()
#4 /sites/enrichedag/wp-includes/class-wp-hook.php(307): ThemeIsle\GutenbergBlocks\Registration->register_blocks()

### How to reproduce:

1. Upgrade (in our environment, see below) to 2.1.2 from 2.1.1
2. see crash.
3. Version 2.1.1 worked properly.

### Expected behaviour:
Not crashing.

### Current behaviour:
Crashing.

### Technical info
* PHP version 8.0.24
* WordPress version: 6.0.3
* Plugin version: 2.1.2
* Environment: wpengine

**Comment by HardeepAsrani** [comment] 2022-11-09 19:51
Hey @dave-andersen,

Thanks for the report. Can you reinstall the plugin to make sure none of the files got corrupted during the update and let us know? 

Let us know and we will check quickly and get this sorted!

**Comment by dave-andersen** [comment] 2022-11-09 19:57
Tested - fails instantly after deleting and re-installing version 2.1.2.

**Comment by HardeepAsrani** [comment] 2022-11-09 20:05
Would you mind email me at hardeep@themeisle.com so we can quickly check the cause?

**Comment by HardeepAsrani** [comment] 2022-11-10 10:00
Hey @dave-andersen,

We were able to figure it out. We've just release version 2.1.3, it should be up on WordPress.org in 10 mins. You can update it and it should be fixed. Let us know how it goes for you!

**Closed** 2022-11-11 08:09 UTC
