### ISSUE TITLE
Updating the plugin breaks blocks

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/otter-blocks#39] opened 2019-01-31 10:17 UTC
After updating the plugin to version 1.1.3 some blocks contain invalid content.
This is happening if you try to import the block. I didn't have it on a page, to test if the blocks keep working properly after updating the plugin.

<img width="1215" alt="neve-footer-error" src="https://user-images.githubusercontent.com/26867648/52047072-eb7d9c80-2550-11e9-8db5-4dea1e3d8eef.png">

I've tried both option `Resolve` and `Convert to HTML` but none of them make the block as it was before. The **template.json** file of the block was edited before adding it in the theme, all occurrences of ```"id": "wp-block-themeisle-blocks-..."``` were removed.
I tried to navigate to manage reusable blocks page, and upload the **template.json** file, it gave me an error, that the file contains invalid content.

From what I see, there is no way to bring the block back from the json file, just rebuild it from scratch. Unfortunately, I don't have more details like the kind of blocks that were used in it, I can't see the initial structure anymore.

A similar situation was happening before when changes were applied to the Section block. All margins were reseted for the already created blocks after updating the plugin.

**Comment by rodica-andronache** [comment] 2019-01-31 10:24
@HardeepAsrani when you have time, if you can share your feedback here it would be great 👍

**Comment by HardeepAsrani** [comment] 2019-01-31 10:39
Thanks. Which blocks are breaking? Which block is it in your screenshot?

**Comment by HardeepAsrani** [comment] 2019-01-31 10:40
You can click on resolve to see the code which will have the className that you can use to tell me the name of the block.

**Comment by HardeepAsrani** [comment] 2019-01-31 10:40
Or you can also attach the JSON of this template.

**Comment by stefan-cotitosu** [comment] 2019-01-31 10:47
Here is the HTML code after I clicked `Convert to HTML`

```
<div class="wp-block-themeisle-blocks-advanced-column" id="wp-block-themeisle-blocks-advanced-column-24946ab0" style="border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;border-style:solid;border-radius:0px">
</div>
```

The broken section within the screenshot is Neve Footer.
<img width="401" alt="broken-section-ss" src="https://user-images.githubusercontent.com/26867648/52049245-fb4baf80-2555-11e9-9ac7-f4d7824f85e8.png">

Below is the json file.
https://github.com/stefan-cotitosu/neve/blob/development/gutenberg/blocks/footer/template.json

Thank you for looking into this 👍

**Comment by radu-themeisle** [comment] 2019-01-31 11:32
I also experienced some issues with the FA icons block, but I managed to fix it by clicking "Resolve". Seems I was lucky...

**Comment by rodica-andronache** [comment] 2019-01-31 13:15
@stefan-cotitosu @HardeepAsrani from what I've tested I've seen this pattern:
1. when 'WooCommerce' and 'WooCommerce Blocks' are installed, none of the Otter blocks are accessible anymore https://prnt.sc/meqwjo
2. when 'Visualizer Lite' is installed, I got this error for most of the blocks https://prnt.sc/meqs0s

**Comment by HardeepAsrani** [comment] 2019-01-31 13:17
1. Yes, the first one was reported yesterday. Weird thing is that it’s inconsistent. It works for me locally but not on poopy. Same happens with the guy who reported it.

2. Will look into this, thanks. 😀

**Comment by rodica-andronache** [comment] 2019-01-31 13:19
yes, it's working without visualizer :) Thanks

**Comment by HardeepAsrani** [comment] 2019-01-31 23:53
@radu-themeisle @stefan-cotitosu Can you check with Font Awesome Block issue? It should be fixed now.

@rodica-andronache For your two issues:

1. WooCommerce issue should be fixed. Now Otter should load, and WooCommerce Blocks shouldn't. 😄  It appears to be an issue on their side, I believe.

2. Can you check if Visualizer issue still happens? I wasn't able to reproduce it on my side.

**Comment by stefan-cotitosu** [comment] 2019-02-01 10:18
@HardeepAsrani For me Font Awesome Block is working well in the latest version of the plugin.

It's not working in version 1.1.2 but I am not sure how relevant is this, as the idea is to have the latest version of the product. The only issue here would be if someone have an older version of Otter and the latest version of Neve which has the blocks in it.

**Comment by rodica-andronache** [comment] 2019-02-01 11:53
@HardeepAsrani the issue with WooCommerce Blocks is fixed for me too, but I still have the problem with Visualizer. Let me know if there is something I can do for this 👍

**Comment by HardeepAsrani** [comment] 2019-02-01 11:53
@stefan-cotitosu We can just ask them to update then, so not an issue. Just need to see what happens with @rodica-andronache

**Comment by HardeepAsrani** [comment] 2019-02-01 11:54
@rodica-andronache I've no idea what's causing them. I mean that particular block has nothing to do with any external library at all.

**Comment by rodica-andronache** [comment] 2019-02-01 12:07
@HardeepAsrani if you can't replicate it, you can check it here. It's only happening for the sections that have font awesome block from what I've seen
http://friendly-cheetah.w5.poopy.life/
user: hardeep
pass: bn8jDTs@PKwCSp&NwU6bE64V

**Comment by HardeepAsrani** [comment] 2019-02-02 23:35
Not yet.

**Closed** 2019-03-08 21:26 UTC
