### ISSUE TITLE
Icon List block icon picker not working for all the lines

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/otter-blocks#1613] opened 2023-04-12 10:46 UTC
### Description

For the Icon List block, when an icon is chosen in the block settings -> Icons -> Icon picker, it doesn't replace the default icons for any of the items. The picker works properly if each Icon List item is selected separately and then the icon is changed just for that item, but nothing happens if you try to change the icon for the entire block.

### Step-by-step reproduction instructions

1. Add and Icon List block
2. Go to Settings -> Icons -> Icon Picker and change the icon
3. Check that nothing changes either in the editor or on the published page

### Screenshots, screen recording, code snippet or Help Scout ticket

![iconlist](https://user-images.githubusercontent.com/86592341/231434678-4015d994-b391-41a4-bf7a-8e30c19a16b2.png)

Reported [here](https://secure.helpscout.net/conversation/2209588184/365371?folderId=212385)

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment] 2023-04-12 11:02
@MarinescuLucia, the new icon are only for newly created items. The old one stays the same.

If you change the icon and create a new item, it will have a new icon. If you change it again, the previous item will stay the same.

**Comment by MarinescuLucia** [comment] 2023-04-12 11:07
@Soare-Robert-Daniel Yes, I noticed that, but I was wondering if it wouldn't be more intuitive for all those 3 default icons to be changed as well if you change it for the entire block? Because, at the moment, you have to select each of those 3 default items and change the icon, even if you change it for the whole block.

**Comment by MarinescuLucia** [comment] 2023-04-12 11:20
Ok Robert, thanks for the details!

**Comment by HardeepAsrani** [comment] 2023-04-12 17:59
I agree with @Soare-Robert-Daniel, it's the intended behavior and not a bug. It's just a quick option to let you select a quick default icon, not managing all from one place.

Closing it now, thank you @MarinescuLucia for reporting.

**Closed by HardeepAsrani** 2023-04-12 17:59 UTC
Labels: bug, customer report
